name: Bazel Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazel-repo
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/MODULE.bazel', '**/WORKSPACE', '**/MODULE.bazel.lock') }}
        restore-keys: |
          ${{ runner.os }}-bazel-

    - name: Install Bazelisk
      uses: bazelbuild/setup-bazelisk@v2

    - name: Build
      run: |
        bazel build //...
      
    - name: Test
      run: |
        bazel test //...